// This file will be auto-generated by Payload CMS
// Run `npm run generate:types` in the admin app to generate these types

export interface User {
  id: string;
  email?: string;
  name?: string;
  role?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Experience {
  id: string;
  title: string;
  slug: string;
  description: any;
  price_from?: number;
  price_to?: number;
  available_dates?: Array<{
    date_range: {
      start_date: string;
      end_date: string;
    }
  }>;
  contact?: {
    phone?: string;
    email?: string;
    website?: string;
  };
  images?: Array<{
    image: string | Media;
  }>;
  publishedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Media {
  id: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  url?: string;
  createdAt: string;
  updatedAt: string;
}

// Add more types as needed...
